server:
  port: 8080 # 项目启动的端口

spring:
  profiles:
    active: dev # 默认激活 dev 本地开发环境

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml

############### Sa-Token配置 ###############
sa-token:
    # token名称
    token-name: satoken
    # token有效期，单位：秒 （默认30天） -1代表永久有效
    timeout: 2592000
    # token临时有效期，单位：秒 （默认-1，代表不临时）
    active-timeout: -1
    # 是否允许同一账号多设备登录 （默认true）
    is-concurrent: true
    # 在多人登录同一账号时，是否共用一个token （默认true）
    is-share: true
    # token风格 可取uuid、simple-uuid、random-32、random-64、random-128、tik
    token-style: uuid
    # 是否输出Sa-Token的日志
    is-log: true

