spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # 指定数据库驱动类
    # 数据库连接信息
    url: jdbc:mysql://13.58.117.104:8888/redbook?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root # 数据库用户名
    password: dsz1314521 # 数据库密码

logging:
  level:
    top.chumi.redbook.auth.domain.mapper: debug
